pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                git 'https://github.com/Sathyaram-Ramadurai/java-web-app.git'
            }
        }

        stage('Build') {
            steps {
                // Build the Java application
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                // Run unit tests
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                // Create a deployable artifact (e.g., WAR or JAR file)
                sh 'mvn package'
            }
        }

       stage('Build Docker Image') {
            steps {
                // Build the Docker image using the Dockerfile in the repository
                sh 'docker build -t docker_web_app .'
            }
        }
        stage('Deploy') {
            steps {
                // Deploy the Docker container using the image on a Docker host
                sh 'docker run -d -p 8090:80 docker_web_app'
            }
        }
    }
}
